/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SupportersRouteImport } from './routes/supporters'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoojaBookingRouteImport } from './routes/pooja-booking'
import { Route as NamaluRouteImport } from './routes/namalu'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportersRoute = SupportersRouteImport.update({
  id: '/supporters',
  path: '/supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojaBookingRoute = PoojaBookingRouteImport.update({
  id: '/pooja-booking',
  path: '/pooja-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const NamaluRoute = NamaluRouteImport.update({
  id: '/namalu',
  path: '/namalu',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/namalu': typeof NamaluRoute
  '/pooja-booking': typeof PoojaBookingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/supporters': typeof SupportersRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/namalu': typeof NamaluRoute
  '/pooja-booking': typeof PoojaBookingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/supporters': typeof SupportersRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/namalu': typeof NamaluRoute
  '/pooja-booking': typeof PoojaBookingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/supporters': typeof SupportersRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/donate'
    | '/gallery'
    | '/journey'
    | '/namalu'
    | '/pooja-booking'
    | '/reset-password'
    | '/story'
    | '/supporters'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/donate'
    | '/gallery'
    | '/journey'
    | '/namalu'
    | '/pooja-booking'
    | '/reset-password'
    | '/story'
    | '/supporters'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/donate'
    | '/gallery'
    | '/journey'
    | '/namalu'
    | '/pooja-booking'
    | '/reset-password'
    | '/story'
    | '/supporters'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  NamaluRoute: typeof NamaluRoute
  PoojaBookingRoute: typeof PoojaBookingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoryRoute: typeof StoryRoute
  SupportersRoute: typeof SupportersRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supporters': {
      id: '/supporters'
      path: '/supporters'
      fullPath: '/supporters'
      preLoaderRoute: typeof SupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pooja-booking': {
      id: '/pooja-booking'
      path: '/pooja-booking'
      fullPath: '/pooja-booking'
      preLoaderRoute: typeof PoojaBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namalu': {
      id: '/namalu'
      path: '/namalu'
      fullPath: '/namalu'
      preLoaderRoute: typeof NamaluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  NamaluRoute: NamaluRoute,
  PoojaBookingRoute: PoojaBookingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoryRoute: StoryRoute,
  SupportersRoute: SupportersRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
